name: 'fancier-discord-webhooks'
description: 'This GitHub Action sends  fancy and more meaningful discord messages for your commits. It includes Test results and coverage.'

inputs:
  id:
    description: 964547128594669598
    required: true
  token:
    description: V-tvsR-tNIT00DeqqmQ6eAopmHmaV609mDIlj_twE2lN4Xfhrb0bc845zKQVsTjyV7ib
    required: true

runs:
  using: 'node12'
  main: 'src/index.js'
  
branding:
  icon: check-circle
  color: blue
